# Others: Sub & Finish
TYPE_ROOT = 1 << 0
TYPE_SUB = 1 << 1
TYPE_FINISH = 1 << 2

OTHERS_SHARED = 1 << 3
OP_OVERWRITE = 1 << 4

STATE_FLAGS = (
    TYPE_ROOT |
    TYPE_SUB |
    TYPE_FINISH |
    OTHERS_SHARED |
    OP_OVERWRITE
)
